### ISSUE TITLE
Via stitching generator ignores Via Grid

### ISSUE THREAD

**Issue by MarkJeronimus** [easyw/RF-tools-KiCAD#11]
Whatever you enter in the Via Grid field, it always places vias ~2.54mm apart (the initial value of the field).

**Comment by easyw** [comment]
@MarkJeronimus 
this should be addressed to via stitching repo
https://github.com/jsreynaud/kicad-action-scripts/tree/master/ViaStitching

**Comment by MarkJeronimus** [comment]
Then why link to your own fork in the readme instead of the original? I didn't even realize it was a fork.

**Comment by easyw** [comment]
@MarkJeronimus 
it is a mistake in the README.md
you can PR a fix to my readme or I will do it later

**Comment by easyw** [comment]
fixed with https://github.com/easyw/RF-tools-KiCAD/commit/7c55601ac1d8aa113286c0ccbec898678717043d
