### ISSUE TITLE
Add RF microwave smooth taper & trace corners

### ISSUE THREAD

**Issue by bvernoux** [easyw/RF-tools-KiCAD#18]
Add RF microwave **smooth taper** & **trace corners** like described in this paper
https://www.changpuak.ch/electronics/downloads/050rfdesign.pdf
smooth taper like in slide 90 =>BEST SMOOTH TAPER
trace corners like in slide 93 => BEST s/d=.7

**Comment by easyw** [comment]
@bvernoux 
this should be already available as [RF-tools-KiCAD#footprint-wizards](https://github.com/easyw/RF-tools-KiCAD#footprint-wizards)

**Comment by bvernoux** [comment]
Thanks for the details/link
