### ISSUE TITLE
KiCAD 5.1.6 support

### ISSUE THREAD

**Issue by IAmSaad** [easyw/RF-tools-KiCAD#21]
I have a 5.1.6 installation and interested in doing RF. Will this be able to work on 5.1.6 or 5.1.7?

**Comment by superbaud** [comment]
I've been using 5.1.8 and this plugin works. I did try nightly about a week ago and it didn't work, for what it's worth.

**Comment by IAmSaad** [comment]
Thankyou. That is great. I wonder why the authors didn't update the KiCAD version requirement on the README
