### ISSUE TITLE
Via Fence Generator Defaults Don't Work

### ISSUE THREAD

**Issue by davidsrsb** [easyw/RF-tools-KiCAD#22]
The default values cause no vias to be placed as the vias are too close to the track
Changing Offeset and Pitch to 1.3/1.3 works, or use smaller vias

**Comment by easyw** [comment]
it should be fixed with this [commit](https://github.com/easyw/RF-tools-KiCAD/commit/6e3c3dd86e6af256fb5105f32962f9544b8e3419)
