### ISSUE TITLE
Curved-Traces - Dialog values not saved 

### ISSUE THREAD

**Issue by airiclenz** [easyw/RF-tools-KiCAD#23]
I need to re-enter the values in the main dialog for the curved traces every single time. This is very tedious and it would be awesome if the dialog could keep the latest settings so when it is opened again, one would not need to re-enter everything.

Also the success confirmation dialog should be optional so that one can switch it off. Error dialogs should still always be shown.

Thanks for the wonderful plugin!

**Comment by superbaud** [comment]
Likewise for the via fence generator dialog; that would be greatly appreciated

**Comment by airiclenz** [comment]
Are there any news / plans regarding this?

**Comment by easyw** [comment]
parameters are now saved with >= v1.2.3 release
