### ISSUE TITLE
Round Tracks

### ISSUE THREAD

**Issue by HaydenHu** [easyw/RF-tools-KiCAD#26]
Can you add the function of adding arcs to other layers of graphic lines to the Round Tracks plug-in? For example, the Edge.Cuts.

**Comment by luczjanoo** [comment]
You can do that by ARC icon in Kicad tools.

![arc](https://user-images.githubusercontent.com/47589390/130147646-8284ab6e-c334-46fa-a2f3-c6019b110ae0.png)

**Comment by HaydenHu** [comment]
I mean like your plug-in, it's convenient to choose two segments at right angles and turn them into fillets!

**Comment by HaydenHu** [comment]
Now that the knightly version of kicad has supported turning a 45-degree angle into an arc, your arc plug-in will not do much more, I hope you can take my advice and change the insert that draws the arc to other coatings, such as a rectangle drawn using the "edge.cut" layer, any two edges on the selected rectangle can automatically turn the right angle into a 90-degree arc, and the selected rectangle can turn all four corners into an arc, which is convenient when drawing the board.

**Comment by easyw** [comment]
fillet trace or drawing is now included in stable kicad release
