### ISSUE TITLE
Python error in Solder Mask Expander.

### ISSUE THREAD

**Issue by luczjanoo** [easyw/RF-tools-KiCAD#27]
Hi.

If I want to start Solder Mask Expander I got error like on screen.

![2021-08-19_233035](https://user-images.githubusercontent.com/47589390/130146982-2306223c-b989-43dd-9fea-cbd0de3a1c68.png)

KiCad version:

![vers](https://user-images.githubusercontent.com/47589390/130147980-39a0d466-396b-4a13-bcea-d12992ccfc55.png)

How to fix it ?

**Comment by albtronics** [comment]
I also have the same issue.
Please help.

**Comment by easyw** [comment]
Hi, I'm porting the code to k 5.99 and this tool is broken atm for k5.1.
I'm going to see if I can maintain a single repo for both of releases as I did for rf fp wizards, round tracks and tracks length.

**Comment by easyw** [comment]
@luczjanoo @albtronics 
it should now be fixed
https://github.com/easyw/RF-tools-KiCAD/commit/d5a5dfef084cbfa374c06784e872ab27754ebdbb

**Comment by albtronics** [comment]
Thank You so much. :)
