### ISSUE TITLE
TraceClearance

### ISSUE THREAD

**Issue by HaydenHu** [easyw/RF-tools-KiCAD#31]
![image](https://user-images.githubusercontent.com/30103277/136701605-13d72216-5504-4c4d-991a-dd396e77c315.png)

Application: KiCad PCB 编辑器 (64-bit)

Version: (5.99.0-12741-g2662433374), release build

Libraries:
	wxWidgets 3.1.5
	libcurl/7.78.0-DEV Schannel zlib/1.2.11

Platform: Windows 10 (build 19043), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Oct  9 2021 12:00:59
	wxWidgets: 3.1.5 (wchar_t,wx containers)
	Boost: 1.76.0
	OCC: 7.5.0
	Curl: 7.78.0-DEV
	ngspice: 35
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

**Comment by easyw** [comment]
@HaydenHu 
I think this is an issue in kicad pcbnew.py API
the function Zone_AddPoligon hasn't changed as definition, but it doesn't work in 5.99
I think we should rise an issue at kicad source code

**Comment by easyw** [comment]
It is fine now.
