### ISSUE TITLE
Enhancement: make trace clearance supports arcs

### ISSUE THREAD

**Issue by CGrassin** [easyw/RF-tools-KiCAD#44]
Currently, the trace clearance tool cannot be used along the track rounder because it does not see arcs as tracks.
It would be nice if it was able to compute a clearance area for arcs.

**Comment by easyw** [comment]
@CGrassin 
thanks for pointing this out... a possible workaround would be when there is an arc to convert it to polyline (like in old RF-tool option) and apply the clearance function to the approximated curve, and finally remove the temporary generated support

**Comment by jacobagilbert** [comment]
Just want to second that this would be a super helpful feature 👍 

I was unable to get your workaround to work in KiCad 7.0.9.
