### ISSUE TITLE
Taper producing wierd shapes

### ISSUE THREAD

**Issue by regicidalplutophage** [easyw/RF-tools-KiCAD#46]
Getting this error in scripting console when attempting to taper round pad to an arc trace segment.
When doing that to a straight segment, KiCad and scripting console both hang.
In both cases malformed zone is added.
```
9:05:04 AM: trackAngle=135.0
9:05:04 AM:  m2 sx=1.7 sy=1.7 nsx=1.7 nsy=1.7
9:05:04 AM:  m2 mod angle=0.0
9:05:04 AM:  t1 sx=1.7 sy=1.7 nsx=1.7 nsy=1.7
9:05:04 AM:  t1 track angle=135.0
9:05:04 AM: targetLength=0.017
9:05:04 AM: vpercent=0.0001
9:05:04 AM: vpercent/100=1e-06
9:05:04 AM: offAngle=0.0 vec[0]=-0.7071067811865476 vec[1]=0.7071067811865476
```

**Comment by regicidalplutophage** [comment]
Just got a similar result in 6.0.3.

**Comment by regicidalplutophage** [comment]
Sorry, that "error" seems to be just some misc info now that I look at it.
Nightly does produce this though:
![taper](https://user-images.githubusercontent.com/36969337/222945510-f8d8eb95-9937-4d0c-abec-04f8cfd86618.PNG)

**Comment by regicidalplutophage** [comment]
Kicad hanging up was misunderstanding on my part, the issue with this plugin generating weird shapes stands
![Снимок](https://user-images.githubusercontent.com/36969337/222960603-f3cc2688-7604-4ea0-b352-d84ea9861931.PNG)

**Comment by easyw** [comment]
@regicidalplutophage 
taper plugin is intended for handling trace to rectangular pads, with pad smaller than track.
Moreover this plugin ATM has mainly limited functionality for near 0° or 90° footprint rotation.

For your user case simply use tear drops (already included in main sw)
https://forum.kicad.info/t/how-to-use-teardrops-in-6-99-7-0-rc1/39522/18

**Comment by regicidalplutophage** [comment]
> @regicidalplutophage taper plugin is intended for handling trace to rectangular pads, with pad smaller than track. Moreover this plugin ATM has mainly limited functionality for near 0° or 90° footprint rotation. ![pcbnew-taper-plugin](https://github.com/easyw/RF-tools-KiCAD/blob/master/resources/pcbnew-taper-plugin.png?raw=true)
> 
> For your user case simply use tear drops (already included in main sw) https://forum.kicad.info/t/how-to-use-teardrops-in-6-99-7-0-rc1/39522/18

I see. I was actually looking for a better solution than native teardrops in 7,0 or the plugin for 6.0 as each has some shortcomings.

**Comment by easyw** [comment]
I'm rewriting the comment I deleted to keep this as reminder for readme file
(thanks for closing the issue):

taper plugin is intended for handling trace to rectangular pads, with pad smaller than track. Moreover this plugin ATM has mainly limited functionality for near 0° or 90° footprint rotation. ![pcbnew-taper-plugin](https://github.com/easyw/RF-tools-KiCAD/blob/master/resources/pcbnew-taper-plugin.png?raw=true)
 
For your user case simply use tear drops (already included in main sw) https://forum.kicad.info/t/how-to-use-teardrops-in-6-99-7-0-rc1/39522/18
