### ISSUE TITLE
All plugins do not recognize the selected object

### ISSUE THREAD

**Issue by HaydenHu** [easyw/RF-tools-KiCAD#48]
![image](https://user-images.githubusercontent.com/30103277/225595768-072d2913-8195-442b-82d3-77bf0ad51f2b.png)
![image](https://user-images.githubusercontent.com/30103277/225595903-2a45df18-5519-453a-8a02-a474ec8535b1.png)
![image](https://user-images.githubusercontent.com/30103277/225596007-259551cc-bfb7-4c81-b772-4eda6d1b9a94.png)

kicad7.0.1
win10

**Comment by easyw** [comment]
@HaydenHu 
1) the message says "you must select two tracks only" but from the image you have selected three objects
2) ??? it is strange
3) you may try disabling 'Removing Vias violatings clearance rules' check box

Could you please add the version of your RF-tools?
And the version of your single tool (simply put the mouse over the tool to get the tooltip with the release info)

**Comment by Raptotype** [comment]
@easyw 

I am seeing exactly the same error on Via fence 3.1 and Rounder 3.1 for Kicad 7.0.8. on Win 11
I tried the reinstall as suggested above but this did not fix it in my case. It seems to just not register any tracks as being selected , regardless of which settings boxes are ticked.

Thank you
