### ISSUE TITLE
Expand the mask on the layer the selected track is on

### ISSUE THREAD

**Issue by brendanarnold** [easyw/RF-tools-KiCAD#5]
**Behaviour**

If you select a track that goes to the back layer through a via and then select the mask expander, it puts the mask on the front layer.

**Expected behavior**

It should apply the mask on the front layer for tracks on the front and the back layer for tracks on the back.

**Comment by brendanarnold** [comment]
PR here https://github.com/easyw/RF-tools-KiCAD/pull/6

**Comment by easyw** [comment]
It should be covered now.
