### ISSUE TITLE
Taper tool crashes KiCAD

### ISSUE THREAD

**Issue by StayWavy1** [easyw/RF-tools-KiCAD#50]
When I went to use the taper tool, KiCAD would immediately crash. Turns out the tool would work when I deleted a certain voltage rail zone I made earlier or edited it to have less of a taper shape that went into a pad.

**Comment by easyw** [comment]
@StayWavy1 
please add a minimal reproducing example, to test the issue.

**Comment by StayWavy1** [comment]
I am unable to upload an example due to confidentiality of the work unfortunately. Guess this can only be more of an FYI for others if they encounter the same issue.
