### ISSUE TITLE
Many tools broken for kicad 8.0

### ISSUE THREAD

**Issue by likecabezon** [easyw/RF-tools-KiCAD#60]
The lenght measuring tools seems to be working but other relevant tools like the taper, the round track or the clearance are broken

**Comment by miguelfaf10** [comment]
With the taper tool the error is:

```
AttributeError: 'BOARD_ITEM_CONTAINER' object had no attribute 'GetOrientationDegrees'
```

**Comment by HaydenHu** [comment]
> With the taper tool the error is:
> 
> ```
> AttributeError: 'BOARD_ITEM_CONTAINER' object had no attribute 'GetOrientationDegrees'
> ```
I've fixed this issue, you can see my pull request

**Comment by arslan437** [comment]
I am having issue with rounding the tracks
![Screenshot 2024-03-20 111544](https://github.com/easyw/RF-tools-KiCAD/assets/55940958/69c91e16-f1b4-41aa-9c27-58e95a2166c0)

**Comment by easyw** [comment]
these errors should be solved now

**Comment by arslan437** [comment]
Thanks updating it
