### ISSUE TITLE
8.0 Kicad has some python file errors.

### ISSUE THREAD

**Issue by josefaneca** [easyw/RF-tools-KiCAD#63]
Hello i have some problems related to the download of the files i have some errors to th via fence generator.
![image](https://github.com/easyw/RF-tools-KiCAD/assets/58661032/1bc15941-6c56-4fd4-8a16-88f4cbcd8f5c)

**Comment by arslan437** [comment]
I am also having some issue with rounding the tracks

![Screenshot 2024-03-20 111544](https://github.com/easyw/RF-tools-KiCAD/assets/55940958/5b37280c-6704-4b63-993b-2c4db122e0e5)

**Comment by easyw** [comment]
these errors should be solved now
